# Generated by Django 5.0.6 on 2024-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='готово'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='description',
            field=models.CharField(default=1, max_length=134, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=12, verbose_name='заголовок'),
        ),
    ]
